name: PushToNuget
env:
  NUGET_DIR: '${{ github.workspace }}/nuget'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  
      - name: Pack Blazor.Diagrams.Core
        working-directory: src/Blazor.Diagrams.Core
        run: 'dotnet pack -p:GeneratePackageOnBuild=false --configuration Release --output ${{ env.NUGET_DIR }}'

      - name: Pack Blazor.Diagrams
        working-directory: src/Blazor.Diagrams
        run: 'dotnet pack -p:GeneratePackageOnBuild=false --configuration Release --output ${{ env.NUGET_DIR }}'

      - name: Pack Blazor.Diagrams.Algorithms
        working-directory: src/Blazor.Diagrams.Algorithms
        run: 'dotnet pack -p:GeneratePackageOnBuild=false --configuration Release --output ${{ env.NUGET_DIR }}'

      - name: Push
        run: |
          foreach($file in (Get-ChildItem "${{ env.NUGET_DIR }}" -Recurse -Include *.nupkg)) {
              dotnet nuget push $file --api-key "${{ secrets.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
          }
